In [1]:
import numpy as np
import pandas as pd

# Q5 

In [6]:
a = pd.read_excel(r'Assignment_05_Data.xlsx',
             sheet_name='5', usecols='BO,BP', skiprows=10,nrows=30, index_col='Year')

In [8]:
Par = a.values.reshape(30)

In [9]:
Par

array([0.07004889, 0.0714037 , 0.07235646, 0.07303536, 0.07352619,
       0.07388659, 0.07415554, 0.07435962, 0.07451707, 0.07464057,
       0.07473899, 0.07481863, 0.07488398, 0.07493832, 0.07498404,
       0.07502293, 0.07505631, 0.07508522, 0.07511044, 0.07513259,
       0.07515215, 0.07516951, 0.075185  , 0.07519886, 0.07521132,
       0.07522254, 0.07523268, 0.07524187, 0.0752502 , 0.07525779])

In [13]:
Duration = np.zeros(30)
for j,i in enumerate(Par):
    PVCF_time = 0
    for ii in range(1,(j*2)+3):
        if(ii==(j*2)+2):
            PVCF_time += (1/((1+Par[j]/2)**(ii)))*(Par[j]*100/2 +100)*ii
        else:
            PVCF_time += (1/((1+Par[j]/2)**(ii)))*(Par[j]*100/2 )*ii
#     print(j,PVCF_time)
    Duration[j] = PVCF_time/200/(1+Par[j]/2)

In [14]:
Duration

array([ 0.94981368,  1.83348377,  2.65399598,  3.41531138,  4.12159331,
        4.77687389,  5.38492985,  5.94925209,  6.47305393,  6.95929269,
        7.41069379,  7.82977329,  8.2188577 ,  8.5801011 ,  8.9154998 ,
        9.22690523,  9.51603523,  9.78448419, 10.03373217, 10.26515326,
       10.48002324, 10.67952661, 10.86476315, 11.03675396, 11.19644704,
       11.34472258, 11.48239771, 11.6102311 , 11.72892703, 11.8391394 ])

In [15]:
pd.DataFrame(Duration).to_clipboard()

# Q6

In [47]:
a = pd.read_excel(r'Assignment_05_Data.xlsx',
             sheet_name='6', usecols='BZ,CA', skiprows=10,nrows=30, index_col='Year')

In [48]:
Par = a.values.reshape(30)

In [49]:
Par

array([0.06999423, 0.07138617, 0.0723584 , 0.07304592, 0.0735388 ,
       0.07389742, 0.07416249, 0.07436163, 0.07451375, 0.0746319 ,
       0.07472517, 0.07479998, 0.07486088, 0.07491114, 0.07495317,
       0.0749887 , 0.07501907, 0.07504527, 0.07506804, 0.07508799,
       0.07510556, 0.07512114, 0.07513501, 0.07514741, 0.07515854,
       0.07516857, 0.07517762, 0.07518582, 0.07519325, 0.07520002])

In [50]:
Duration = np.zeros(30)
for j,i in enumerate(Par):
    PVCF_time = 0
    for ii in range(1,(j*2)+3):
        if(ii==(j*2)+2):
            PVCF_time += (1/((1+Par[j]/2)**(ii)))*(Par[j]*100/2 +100)*ii
        else:
            PVCF_time += (1/((1+Par[j]/2)**(ii)))*(Par[j]*100/2 )*ii
    Duration[j] = PVCF_time/200/(1+Par[j]/2)

In [51]:
pd.DataFrame(Duration).to_clipboard()